#!/bin/sh
# install.sh - @cosasdepuma dotfiles installer
# Usage:
#   Install: curl -fsSL https://dotfiles.kike.wtf/ | sh
#   Update:  dotfiles

# =======================
#   Setup
# =======================
set -e

# change to the dotfiles directory and download/update dotfiles itself first
if ! test -d ~/.cache/dotfiles; then
    git clone --quiet --depth 1 https://github.com/cosasdepuma/.dotfiles ~/.cache/dotfiles
fi
cd ~/.cache/dotfiles || exit 1
git pull --quiet --ff-only

# define a function to sync dotfiles
sync() {
    rsync -gortu --no-p \
      --exclude .git \
      --exclude .github \
      --exclude LICENSE \
      "$@" || exit 1
    if

}

# =======================
#   Installation
# =======================
# widely used dotfiles
sync .curlrc .ssh .wgetrc ~/
sync .config/git ~/.config/
sync .bin/dotfiles ~/.bin/

# =======================
#   Permissions
# =======================
# ensure that the dotfiles are readable
chmod -R u+r ~/.[!.]*
# ensure that the dotfiles binaries are executable
chmod -R u+x ~/.bin/

# =======================
#   Clean up
# =======================
unset sync