#!/bin/sh

export SWWW_INTERVAL=300

test -f "${XDG_RUNTIME_DIR}/swww.socket" && rm -f "${XDG_RUNTIME_DIR}/swww.socket"
test -d "${HOME}/.cache/swww" && rm -rf "${HOME}/.cache/swww"

swww init
while :; do
  random_img=$(find ~/.config/wallpapers | shuf -n 1)
  if test -f ${random_img}; then
    swww img --transition-type grow --transition-duration 3 "${random_img}"
    sleep "${SWWW_INTERVAL}"
  fi
done