#!/bin/zsh

# -- 📛 aliases ---

# cat -> bat
alias cat='bat --paging=never'
alias catl='bat'
alias catn='cat --plain --paging=never'

# ls -> lsd
alias l='ls -alh'
alias la='lsd -a'
alias ll='lsd -l'
alias lla='lsd -la'
alias ls='lsd'

# --- ⏹️ avoid first-time message (the second time) ---

echo "#" > ~/.zshrc

# --- 📌 enable git ---

autoload -Uz vcs_info
precmd_functions+=( vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats ' %F{10}%u[%b]%f'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '%F{3}'
zstyle ':vcs_info:*' enable git

# --- 📢 prompts ---

# left side: icon(root indicator) + user@host + pwd
if test "${EUID}" -ne 0; then isroot=15; else isroot=13; fi
PROMPT='%F{$isroot}🐰%f %F{12}%n@%m%f%b %F{14}%2~%f${vcs_info_msg_0_} '
# right side: status code
RPROMPT='%(?..%F{1}(%?%) %f)'

# --- 🎨 theme ---

# save a color into the palette:: name -> color
function set_color {
	if [ "$TERM" = "linux" ]; then
		[ $1 -lt 16 ] && printf $'\e]P%X%s' "$1" "$2"
	else
		printf $'\e]4;%s;#%s\e\\' "$1" "$2"
	fi
}

# terminal colors (gruvbox theme).
local black=1d2021
local white=dadada
printf "\e]10;#$white"
printf "\e]11;#$black"
set_color  0 $black # black
set_color  1 cc241d # red
set_color  2 98971a # green
set_color  3 d79921 # yellow
set_color  4 458588 # blue
set_color  5 b16286 # magenta
set_color  6 689d6a # cyan
set_color  7 928374 # light grey
set_color  8 282828 # dark grey
set_color  9 fb4934 # bright red
set_color 10 b8bb26 # bright green
set_color 11 fabd2f # bright yellow
set_color 12 83a598 # bright blue
set_color 13 d3869b # bright magenta
set_color 14 8ec07c # bright cyan
set_color 15 $white # white
set_color 17 076678 # dark blue
set_color 22 79740e # dark green
set_color 52 9d0006 # dark red
set_color 53 8f3f71 # dark magenta
